title: Pessimistic Operator # The title of the blog
author: Martin Roberts # Your name 
email: dokoissho@sdf.org # your email shown in the footer
baseurl: "/pessimistic-operator" # this is your site's root address.
url: ""
description: # this means to ignore newlines until "show_excerpts:"
  Web publishing for the rest of us
show_excerpts: false # set to true to show excerpts on the homepage
livereload: true
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  # avatar_url: "https://avatars.githubusercontent.com/u/8925762?s=400&v=4" # avatar in about page
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: mroberts333 
    github:  mroberts1
    # rss: RSS
    # dribbble: 
    facebook: mr05301
    # flickr:   
    # instagram: 
    # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    telegram: dokoissho
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    mastodon:
     - username: dokoissho  
       instance: merveilles.town
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-menus
